# ------------------------------------------------------------------------------
# playbook-argocd.yml
# ------------------------------------------------------------------------------
- name: Install ArgoCD on AKS Cluster
  hosts: bastion # This runs on the bastion, which has kubectl access
  connection: local
  become: false # No sudo needed for kubectl commands
  roles:
    - role: argocd_install 