---
# roles/jenkins-server/tasks/install_aws_cli.yml

- name: Download AWS CLI v2 bundle
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI bundle
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Install AWS CLI v2
  ansible.builtin.shell: |
    /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Verify AWS CLI installation
  ansible.builtin.command: aws --version
  register: aws_cli_version
  changed_when: false

- name: Show installed AWS CLI version
  ansible.builtin.debug:
    var: aws_cli_version.stdout