# ------------------------------------------------------------------------------
# roles/tools_install/tasks/main.yml (Azure)
# ------------------------------------------------------------------------------
- name: Install base dependencies and tools
  ansible.builtin.apt:
    name:
      - git
      - unzip
      - docker.io
      - kubectl
    state: present
    update_cache: yes

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ansible_user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Add jenkins user to the docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: Install Helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.15.1-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts: [--strip-components=1, linux-amd64/helm]

- name: Install ArgoCD CLI
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/v2.11.1/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: '0755'

- name: Install Kustomize
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts: [kustomize]

- name: Install Trivy
  ansible.builtin.unarchive:
    src: https://github.com/aquasecurity/trivy/releases/download/v0.51.1/trivy_0.51.1_Linux-64bit.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts: [trivy]

- name: Install Azure CLI for Jenkins user
  ansible.builtin.apt:
    name: azure-cli
    state: present
  become: true

- name: Configure kubectl for the jenkins user
  ansible.builtin.shell: "az login --identity && az aks get-credentials --resource-group {{ resource_group_name }} --name {{ aks_cluster_name }} --overwrite-existing"
  args:
    creates: "{{ jenkins_user_dir }}/.kube/config"
  become: true
  become_user: jenkins 