# ------------------------------------------------------------------------------
# roles/bastion_setup/tasks/main.yml
# ------------------------------------------------------------------------------
- name: Update all system packages
  ansible.builtin.package:
    name: "*"
    state: latest
  vars:
    ansible_command_timeout: 600

- name: Install base CLI tools (awscli, git, unzip)
  ansible.builtin.package:
    name:
      - awscli
      - git
      - unzip
    state: present

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    dest: /tmp/kubectl
    mode: '0755'

- name: Install kubectl to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Download eksctl archive
  ansible.builtin.get_url:
    url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
    dest: /tmp/eksctl.tar.gz

- name: Unarchive eksctl
  ansible.builtin.unarchive:
    src: /tmp/eksctl.tar.gz
    dest: /tmp
    remote_src: true

- name: Install eksctl to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/eksctl
    dest: /usr/local/bin/eksctl
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Configure kubectl to access EKS cluster
  ansible.builtin.shell: "aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}"
  args:
    creates: "{{ ansible_user_dir }}/.kube/config"
  become: false # Run as the ansible_user, not root

- name: Test kubectl connection
  ansible.builtin.command: "kubectl get nodes"
  register: kubectl_get_nodes
  changed_when: false
  become: false

- name: Display kubectl get nodes output
  ansible.builtin.debug:
    msg: "{{ kubectl_get_nodes.stdout }}" 