# ------------------------------------------------------------------------------
# roles/argocd_install/tasks/main.yml
#
# Assumes kubectl is configured on the machine running this playbook (the bastion).
# Requires the `kubernetes.core` collection: `ansible-galaxy collection install kubernetes.core`
# ------------------------------------------------------------------------------
- name: Ensure kubernetes.core collection is present
  ansible.builtin.command: ansible-galaxy collection install kubernetes.core
  changed_when: false

- name: Create argocd namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Install ArgoCD using official manifest
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    src: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"

- name: Wait a moment for the secret to be created
  ansible.builtin.pause:
    seconds: 30

- name: Get initial ArgoCD admin password
  ansible.builtin.shell: >
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_password
  changed_when: false

- name: Display initial ArgoCD admin password
  ansible.builtin.debug:
    msg:
      - "ArgoCD initial admin password -> {{ argocd_password.stdout }}"
      - "To access the UI, run this command from your bastion:"
      - "kubectl port-forward svc/argocd-server -n argocd 8080:443"
      - "Then open https://localhost:8080 in your browser." 