---
{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled $svc.stateful }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $svcName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $svcName }}
    release: {{ $.Release.Name }}
spec:
  serviceName: {{ $svcName }}
  replicas: {{ $svc.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ $svcName }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $svcName }}
        release: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $svcName }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          {{- if $svc.env }}
          env:
          {{- toYaml $svc.env | nindent 12 }}
          {{- end }}
          {{- if $svc.resources }}
          resources:
          {{- toYaml $svc.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $svc.service.port }}
              name: {{ $svcName }}
          {{- if $svc.securityContext }}
          securityContext:
          {{- toYaml $svc.securityContext | nindent 12 }}
          {{- end }}
          {{- if $svc.livenessProbe }}
          livenessProbe:
          {{- toYaml $svc.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $svc.readinessProbe }}
          readinessProbe:
          {{- toYaml $svc.readinessProbe | nindent 12 }}
          {{- end }}
      nodeSelector:
      {{- toYaml $.Values.global.nodeSelector | nindent 8 }}
  {{- if $svc.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ $svcName }}
        release: {{ $.Release.Name }}
    spec:
      accessModes:
        - {{ $svc.persistence.accessMode }}
      storageClassName: {{ $svc.persistence.storageClass }}
      resources:
        requests:
          storage: {{ $svc.persistence.size }}
  {{- end }}
---
{{- end }}
{{- end }}