{{- range $svcName, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $svcName }}
    release: {{ $.Release.Name }}
    role: service
  annotations:
{{- if $svc.service.annotations }}
{{ toYaml $svc.service.annotations | indent 4 }}
{{- else }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ $svc.service.port }}"
{{- end }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  ports:
    - name: {{ $svcName }}
      port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}
      {{- if eq $svc.service.type "NodePort" }}
      nodePort: {{ $svc.service.nodePort }}
      {{- end }}
  selector:
    app: {{ $svcName }}
    release: {{ $.Release.Name }}
---
{{- end }}
{{- end }}