---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: sock-shop
  labels:
    name: carts
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: carts
