---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: sock-shop
  labels:
    name: carts-db
    app: sock-shop
    role: database
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: carts-db
