---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  namespace: sock-shop
  labels:
    name: queue-master
    app: sock-shop
    role: queue-master
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: queue-master
    app: sock-shop
    role: queue-master
