---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: sock-shop
  labels:
    name: rabbitmq
    app: sock-shop
    role: message-broker
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: ClusterIP
  ports:
    - port: 5672
      name: rabbitmq
      targetPort: 5672
      protocol: TCP
    - port: 9090
      name: exporter
      targetPort: 9090
      protocol: TCP
  selector:
    name: rabbitmq
    app: sock-shop
    role: message-broker
