---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  namespace: sock-shop
  labels:
    name: session-db
    app: sock-shop
    role: session-db
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: session-db
    app: sock-shop
    role: session-db
