---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  namespace: sock-shop
  labels:
    name: session-db
    app: sock-shop
    role: session-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: session-db
      app: sock-shop
      role: session-db
  template:
    metadata:
      labels:
        name: session-db
        app: sock-shop
        role: session-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: session-db
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
      nodeSelector:
        beta.kubernetes.io/os: linux
