---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: sock-shop
  labels:
    name: shipping
    app: sock-shop
    role: shipping
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: shipping
    app: sock-shop
    role: shipping
