---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: sock-shop
  labels:
    name: user
    app: sock-shop
    role: user
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: user
    app: sock-shop
    role: user
