---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: sock-shop
  labels:
    name: user-db
    app: sock-shop
    role: database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
      app: sock-shop
      role: database
  template:
    metadata:
      labels:
        name: user-db
        app: sock-shop
        role: database
    spec:
      containers:
      - name: user-db
        image: weaveworksdemos/user-db:0.3.0
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 999  # MongoDB often uses UID 999, adjust if needed
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
